### ISSUE TITLE
Replicate layout failure

### ISSUE THREAD

**Issue by pendragon8991** [MitjaNemec/ReplicateLayout#47]
Hello, i have an issues every time i try to use the plugin to replicate my sheets. 
A fatal error stop the process after only one (in a sheet of 70) footprint moves in a random position. I attached the log file images.
![rep](https://user-images.githubusercontent.com/68713074/231473332-cbeeb5ec-2472-43bc-9d32-72adba614165.JPG)
I have the same issues (and error message) also using save/restore plugin on the same project.

**Comment by MitjaNemec** [comment]
This is the same issue as PlaceFootprints#14. Update the "pcbnewTransition"

**Comment by pendragon8991** [comment]
I tried to update (however i download the plugin that use that today, so i think was already the last version) and nothing change.

**Comment by MitjaNemec** [comment]
The issue is not with the version of "Replicate Layout" plugin. You have either installed "pcbneeTransition" directly or you installed some other plugin, which also installed "pcbnewTransition"

"PcbnewTransition" modifies (monkeypatches) pcbnew python API for all plugin. And there is a bug in the version that you've installed.

**Comment by MitjaNemec** [comment]
Maybe you can ask codman256 in the mentioned issue how he solved this

**Comment by MitjaNemec** [comment]
You should raise the issue with the KiKit author for two reasons:
1. So that he will be aware of this issue
2. that he might implement update mechanism for his dependency
