### ISSUE TITLE
Does not replicate traces in KiCad 7.02

### ISSUE THREAD

**Issue by TchDuke** [MitjaNemec/ReplicateLayout#52]
![KiCadVer](https://user-images.githubusercontent.com/131647301/233921410-ae3dee95-cee0-4dcf-849f-f551b0d6d178.PNG)
![RL_Issue](https://user-images.githubusercontent.com/131647301/233920923-3cf80b2c-9235-49ed-8523-557d772723fe.PNG)
[replicate_layout.log](https://github.com/MitjaNemec/ReplicateLayout/files/11307525/replicate_layout.log)

**Comment by MitjaNemec** [comment]
Thanks for reporting. It looks like there were a number of changes in python API from 7.0.1 to 7.0.2. This might be related to https://gitlab.com/kicad/code/kicad/-/issues/13921

And is duplicate to issue #51, but since that one is closed, I'll track this issue here

**Comment by MitjaNemec** [comment]
This is the same as #49. So if you are in a hurry you can patch it locally. Otherwise you'll have to wait a bit

**Comment by elektronchika** [comment]
I have the very same log as posted. Placement is replicated, routing not. 

BTW - great plugin, I use it a lot :)

**Comment by rigustafson** [comment]
Same error here

**Comment by MitjaNemec** [comment]
First of all, thanks for reporting this.

As it turns out this is due to a bug in KiCad. It got introduce just before the 7.0.2 release with [8e579ec8](https://gitlab.com/kicad/code/kicad/-/commit/8e579ec8e0e8d485645d18cb5d897fc2174307c5) and got fixed just after the 7.0.2 was tagged in [7843e6a7](https://gitlab.com/kicad/code/kicad/-/commit/7843e6a70904e9960114a0dc6cfff816b27c116f).

Anyhow, the fix for this is in [2.0.12](https://github.com/MitjaNemec/ReplicateLayout/releases/tag/2.0.12) release, which is available for installation from file and should be available in PCM in a couple of days.
