### ISSUE TITLE
Fatal error: AttributeError: 'BOARD_ITEM' object has no attribute 'SetNetCode'

### ISSUE THREAD

**Issue by greenscreenflicker** [MitjaNemec/ReplicateLayout#53]
![grafik](https://github.com/MitjaNemec/ReplicateLayout/assets/17407241/fdd95c85-b547-4611-aef8-f055ab256b7f)
The log is attached.
[replicate_layout.log](https://github.com/MitjaNemec/ReplicateLayout/files/11432474/replicate_layout.log)

**Comment by MitjaNemec** [comment]
First of all, thanks for reporting this.

As it turns out this is due to a bug in KiCad. It got introduce just before the 7.0.2 release with [8e579ec8](https://gitlab.com/kicad/code/kicad/-/commit/8e579ec8e0e8d485645d18cb5d897fc2174307c5) and got fixed just after the 7.0.2 was tagged in [7843e6a7](https://gitlab.com/kicad/code/kicad/-/commit/7843e6a70904e9960114a0dc6cfff816b27c116f).

Anyhow, the fix for this is in [2.0.12](https://github.com/MitjaNemec/ReplicateLayout/releases/tag/2.0.12) release, which is available for installation from file and should be available in PCM in a couple of days.

**Comment by tobimai** [comment]
I had the same bug, just updated via Kicad Addon manager and can confirm it's now gone.

**Comment by MitjaNemec** [comment]
@tobimai , thanks for reporting back
